version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: order-security-rules
    binary: order-security-rules_{{ .Os }}_{{ .Arch }}
    no_unique_dist_dir: true
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    targets:
    - darwin_arm64
    - darwin_amd64
    - linux_amd64
    - linux_arm64
    